# Generated by Django 3.2.3 on 2021-06-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('logradouro', models.CharField(max_length=80, verbose_name='logradouro')),
                ('bairro', models.CharField(max_length=80, verbose_name='baurro')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('telefone', models.IntegerField(verbose_name='telefone')),
                ('cnpj', models.IntegerField(unique=True, verbose_name='cnpj')),
            ],
            options={
                'verbose_name': 'Abrigo',
                'verbose_name_plural': 'Abrigos',
                'db_table': 'abrigo',
            },
        ),
    ]
