# Generated by Django 3.2.3 on 2021-06-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrigo',
            name='bairro',
            field=models.CharField(max_length=80, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='abrigo',
            name='cnpj',
            field=models.CharField(max_length=13, unique=True, verbose_name='cnpj'),
        ),
        migrations.AlterField(
            model_name='abrigo',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='telefone'),
        ),
    ]
